name: Testing-LTS — Build and Publish

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    uses: highwaytoit/dakota-lts/.github/workflows/testing-lts-publish.yml@testing-lts
