name: Run Dakota LTS worker build

on:
  workflow_dispatch:
    inputs:
      variant:
        description: Image variant to build on worker-dakota
        required: true
        default: default
        type: choice
        options:
          - default
          - nvidia

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: highwaytoit/dakota-lts/.github/workflows/local-worker-build.yml@testing-lts
    with:
      variant: ${{ inputs.variant }}
