name: Recovery build trigger

on:
  push:
    branches:
      - testing-lts
    paths:
      - .github/workflows/recovery-build.yml

permissions:
  contents: read

jobs:
  build:
    uses: highwaytoit/dakota-lts/.github/workflows/local-worker-build.yml@testing-lts
    with:
      variant: default
